version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: artemzakharov/tryout
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 1024M
      restart_policy:
        condition: on-failure
    environment: 
      URL: "localhost"
      SSL: "false"
      PORT: "4200"
    ports:
      - "4200:4200"
    networks:
      - webnet
networks:
  webnet: